[build]
  command = "pnpm run build"
  publish = "build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "16"
  
[[plugins]]
  package = "/netlify-plugin-pnpm"
